variables:
  IMAGE_ORG: kotahi
  IMAGE_NAME: kotahi-elife
  REGION: us-east-1
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_USER: kotahidev
  POSTGRES_PASSWORD: kotahidev
  PGUSER: kotahidev
  PGPASSWORD: kotahidev

stages:
  #- cache
  - build
  #- deploy
  - test

# cache:
#   image:
#     name: banst/awscli
#     entrypoint: [""]
#   script:
#     - aws configure set region $REGION
#     - aws s3 cp s3://elife-node-modules/node_modules_dev.tar.gz .

build:
  image: docker:20.10.5
  variables:
    DOCKER_BUILDKIT: 1
  services:
    - docker:20.10.5-dind
  stage: build
  # dependencies:
  #   - cache
  before_script:
    - cp app/brand-instances-configs/elife.json app/brandConfig.json
  script:
    - |
      if [ -z "$DOCKERHUB_USERNAME_ELIFE" ] || [ -z "$DOCKERHUB_PASSWORD_ELIFE" ]; then echo "Not pushing" && exit 0; fi
      docker login -u $DOCKERHUB_USERNAME_ELIFE -p $DOCKERHUB_PASSWORD_ELIFE
      docker pull $IMAGE_ORG/$IMAGE_NAME-dev:latest || true
      docker build --build-arg instance_name=elife --build-arg manuscripts_table_columns=submission.articleId,created,updated,status,author --file ./Dockerfile-ci --cache-from $IMAGE_ORG/$IMAGE_NAME-dev:latest --tag $IMAGE_ORG/$IMAGE_NAME-dev:$CI_COMMIT_SHA --tag $IMAGE_ORG/$IMAGE_NAME-dev:latest .
      docker push $IMAGE_ORG/$IMAGE_NAME-dev:$CI_COMMIT_SHA
      docker push $IMAGE_ORG/$IMAGE_NAME-dev:latest
      # docker build \
      # --build-arg instance_name=elife \
      # --build-arg public_client_host=elife.kotahi.cloud \
      # --build-arg public_client_port=443 \
      # --build-arg public_client_protocol=https \
      # --file ./Dockerfile-production-elife \
      # --cache-from $IMAGE_ORG/$IMAGE_NAME:latest \
      # --tag $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA \
      # --tag ${env.IMAGE_ORG}/${env.IMAGE_NAME}:latest .
      # docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
      # docker push $IMAGE_ORG/$IMAGE_NAME:latest
      # rm -rf node_modules_dev.tar.gz

# deploy:
#   stage: deploy
#   image: ubuntu:18.04
#   script:
#     - |
#       aws --region=$REGION eks update-kubeconfig --name eks-elife-kotahi
#       curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
#       curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
#       apt-get install apt-transport-https --yes
#       echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
#       echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
#       apt-get update
#       apt-get install helm kubectl -y
#       #helm del elife-kotahi-prod
#       helm upgrade elife-kotahi-prod ./helm/kotahi \
#       --set images.backend.repository=$IMAGE_ORG/$IMAGE_NAME \
#       --set images.backend.tag=$CI_COMMIT_SHA \
#       --set images.jobxsweet.repository=pubsweet/job-xsweet \
#       --set images.jobxsweet.tag=1.5.1 \
#       --set backend.deployment.containerPort=3000 \
#       --set backend.ingress.port=80 \
#       --set backend.ingress.targetPort=3000 \
#       --set backend.service.port=80 \
#       --set backend.service.targetPort=3000 \
#       --set rdssecret=elife-kotahi-prod-rds-postgres \
#       --set s3secret=elife-kotahi-prod-s3-attachment \
#       --install \
#       --force \
#       --wait
#       helm ls
#       kubectl get pods | grep server && kubectl get pods | grep job-xsweet

lint:
  allow_failure: true
  image: $IMAGE_ORG/$IMAGE_NAME-dev:latest
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${HOME}
    - npm run lint

.test_template: &run_test_template
  image: $IMAGE_ORG/$IMAGE_NAME-dev:latest
  stage: test
  variables:
    GIT_STRATEGY: none
  services:
    - postgres

.test_before_script: &run_test_before_script
  - apt-get update
  - apt-get -y install postgresql-client
  - psql -h postgres -U kotahidev -d kotahidev -c "create extension pgcrypto;"

.test_script: &run_test_script
  - cd ${HOME}
  - cp .env.example .env
  - POSTGRES_HOST=postgres yarn test:all:$TEST_ITEM

test-chrome:
  before_script:
    - *run_test_before_script
  <<: *run_test_template
  variables:
    TEST_ITEM: 'chrome:elife'
  script:
    - *run_test_script
## commented Wed May 12 15:55:40 EEST 2021 by beatrice.suarasan@endava.com request
# test-chrome-samsung:
#   before_script:
#     - *run_test_before_script
#   <<: *run_test_template
#   variables:
#     TEST_ITEM: "chrome:elife:samsung"
#   script:
#     - *run_test_script

# test-chrome-samsung-tablet:
#   before_script:
#     - *run_test_before_script
#   <<: *run_test_template
#   variables:
#     TEST_ITEM: "chrome:elife:samsung:tablet"
#   script:
#     - *run_test_script

# test-chrome-iPhone:
#   before_script:
#     - *run_test_before_script
#   <<: *run_test_template
#   variables:
#     TEST_ITEM: "chrome:elife:iPhone"
#   script:
#     - *run_test_script

# test-chrome-iPhone-tablet:
#   before_script:
#     - *run_test_before_script
#   <<: *run_test_template
#   variables:
#     TEST_ITEM: "chrome:elife:iPhone:tablet"
#   script:
#     - *run_test_script

# test-chrome-hd-laptop:
#   before_script:
#     - *run_test_before_script
#   <<: *run_test_template
#   variables:
#     TEST_ITEM: "chrome:elife:hd:laptop"
#   script:
#     - *run_test_script

