variables:
  IMAGE_ORG: simplej
  IMAGE_NAME: simplej

stages:
  - build
  - test
  # - review
  # - staging
  # - production
  # - demo

build:
  image: docker:20.10.5
  variables:
    DOCKER_BUILDKIT: 1
  services:
    - docker:20.10.5-dind
  stage: build
  before_script:
    - cp app/brand-instances-configs/coko.json app/brandConfig.json
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker pull $IMAGE_ORG/$IMAGE_NAME:latest || true
    - docker build --file ./Dockerfile-ci --cache-from $CI_REGISTRY_IMAGE:latest --tag $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA --tag $IMAGE_ORG/$IMAGE_NAME:latest .
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_ORG/$IMAGE_NAME:latest

lint:
  allow_failure: true
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${HOME}
    - npm run lint

test-chrome:
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
    # setup data for postgres image
    POSTGRES_USER: kotahitest
    POSTGRES_PASSWORD: pw
    # connection details for tests
    PGUSER: kotahitest
    PGPASSWORD: pw
    NODE_ENV: test
  services:
    - postgres
  script:
    - cd ${HOME}
    - apt-get -y install postgresql-client
    # this is needed for pgboss initial setup
    - psql -h postgres -U kotahitest -d kotahitest -c "create extension pgcrypto;"
    # specify host here else it confuses the linked postgres image
    - PGHOST=postgres yarn test:all:chrome

test-firefox:
  allow_failure: true # at this point Cypress' support for Firefox is not stable
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
    # setup data for postgres image
    POSTGRES_USER: kotahitest
    POSTGRES_PASSWORD: pw
    # connection details for tests
    PGUSER: kotahitest
    PGPASSWORD: pw
    NODE_ENV: test
  services:
    - postgres
  script:
    - cd ${HOME}
    - apt-get -y install postgresql-client
    # this is needed for pgboss initial setup
    - psql -h postgres -U kotahitest -d kotahitest -c "create extension pgcrypto;"
    # specify host here else it confuses the linked postgres image
    - PGHOST=postgres yarn test:all:firefox
