variables:
  IMAGE_ORG: kotahi
  IMAGE_NAME: kotahi-elife

stages:
  #- build
  - deploy

# build:
#   image: docker:20.10.5
#   variables:
#     DOCKER_BUILDKIT: 1
#   services:
#     - docker:20.10.5-dind
#   stage: build
#   before_script:
#     - cp app/brand-instances-configs/elife.json app/brandConfig.json
#   script:
#     - |
#       if [ -z "$DOCKERHUB_USERNAME_ELIFE" ] || [ -z "$DOCKERHUB_PASSWORD_ELIFE" ]; then echo "Not pushing" && exit 0; fi
#       docker login -u $DOCKERHUB_USERNAME_ELIFE -p $DOCKERHUB_PASSWORD_ELIFE
#       docker pull $IMAGE_ORG/$IMAGE_NAME:latest || true
#       docker build \
#       --build-arg instance_name=elife \
#       --build-arg public_client_host=elife.kotahi.cloud \
#       --build-arg public_client_port=443 \
#       --build-arg public_client_protocol=https \
#       --file ./Dockerfile-production \
#       --cache-from $CI_REGISTRY_IMAGE:latest \
#       --tag $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA \
#       --tag $IMAGE_ORG/$IMAGE_NAME:latest .
#       docker build --build-arg instance_name=elife --file ./Dockerfile-ci --cache-from $IMAGE_ORG/$IMAGE_NAME-dev:latest --tag $IMAGE_ORG/$IMAGE_NAME-dev:$CI_COMMIT_SHA --tag $IMAGE_ORG/$IMAGE_NAME-dev:latest .
#       docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
#       docker push $IMAGE_ORG/$IMAGE_NAME:latest
#       docker push $IMAGE_ORG/$IMAGE_NAME-dev:$CI_COMMIT_SHA
#       docker push $IMAGE_ORG/$IMAGE_NAME-dev:latest

deploy:
  stage: deploy
  image: jshimko/kube-tools-aws:latest
  variables:
    AWS_ACCESS_KEY_ID: $ELIFE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $ELIFE_AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $ELIFE_AWS_DEFAULT_REGION
    ELIFE_CLUSTER_NAME: eks-elife-kotahi
  before_script:
     - mkdir ~/.kube && touch ~/.kube/config
     - echo "${ELIFE_K8S_CLUSTER_CONFIG}" >> ~/.kube/config
  script:
      - |
        aws --region=$AWS_DEFAULT_REGION eks update-kubeconfig --name $ELIFE_CLUSTER_NAME
        helm repo list
        # helm repo add kotahi https://charts.bitnami.com/bitnami
        # helm dependency build helm/elife-kotahi
        # helm upgrade -i elife-kotahi \
        #       --set hostname=k8s.kotahi.cloud \
        #       --wait \
        #       helm/elife-kotahi

