variables:
  IMAGE_ORG: kotahi
  IMAGE_NAME: kotahi-colab
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_USER: kotahidev
  POSTGRES_PASSWORD: kotahidev
  PGUSER: kotahidev
  PGPASSWORD: kotahidev

stages:
  - build
  - test

build:
  image: docker:20.10.5
  variables:
    DOCKER_BUILDKIT: 1
  services:
    - docker:20.10.5-dind
  stage: build
  before_script:
    - cp app/brand-instances-configs/colab.json app/brandConfig.json
  script:
    - |
      if [ -z "$DOCKERHUB_USERNAME_ELIFE" ] || [ -z "$DOCKERHUB_PASSWORD_ELIFE" ]; then echo "Not pushing" && exit 0; fi
      docker login -u $DOCKERHUB_USERNAME_ELIFE -p $DOCKERHUB_PASSWORD_ELIFE
      docker pull $IMAGE_ORG/$IMAGE_NAME-dev:latest || true
      docker build --build-arg instance_name=colab --build-arg manuscripts_table_columns=meta.title, created, updated, status, submission.labels, author --file ./Dockerfile-ci --cache-from $IMAGE_ORG/$IMAGE_NAME-dev:latest --tag $IMAGE_ORG/$IMAGE_NAME-dev:$CI_COMMIT_SHA --tag $IMAGE_ORG/$IMAGE_NAME-dev:latest .
      docker push $IMAGE_ORG/$IMAGE_NAME-dev:$CI_COMMIT_SHA
      docker push $IMAGE_ORG/$IMAGE_NAME-dev:latest

.test_template: &run_test_template
  image: $IMAGE_ORG/$IMAGE_NAME-dev:latest
  stage: test
  variables:
    GIT_STRATEGY: none
  services:
    - postgres

.test_before_script: &run_test_before_script
  - apt-get update
  - apt-get -y install postgresql-client
  - psql -h postgres -U kotahidev -d kotahidev -c "create extension pgcrypto;"

.test_script: &run_test_script
  - cd ${HOME}
  - cp .env.example .env
  - POSTGRES_HOST=postgres yarn test:all:$TEST_ITEM

test-firefox:
  before_script:
    - *run_test_before_script
  <<: *run_test_template
  variables:
    TEST_ITEM: 'firefox:colab'
  script:
    - *run_test_script

test-firefox-samsung:
  before_script:
    - *run_test_before_script
  <<: *run_test_template
  variables:
    TEST_ITEM: 'firefox:colab:samsung'
  script:
    - *run_test_script

test-firefox-samsung-tablet:
  before_script:
    - *run_test_before_script
  <<: *run_test_template
  variables:
    TEST_ITEM: 'firefox:colab:samsung:tablet'
  script:
    - *run_test_script

test-firefox-iPhone:
  before_script:
    - *run_test_before_script
  <<: *run_test_template
  variables:
    TEST_ITEM: 'firefox:colab:iPhone'
  script:
    - *run_test_script

test-firefox-iPhone-tablet:
  before_script:
    - *run_test_before_script
  <<: *run_test_template
  variables:
    TEST_ITEM: 'firefox:colab:iPhone:tablet'
  script:
    - *run_test_script

test-firefox-hd-laptop:
  before_script:
    - *run_test_before_script
  <<: *run_test_template
  variables:
    TEST_ITEM: 'firefox:colab:hd:laptop'
  script:
    - *run_test_script
