#FROM cypress/browsers:node14.16.0-chrome89-ff86 // cypress test cases are failing in gitlab hence disabling node 14
FROM cypress/browsers:node12.18.3-chrome89-ff86

ARG instance_name
ARG node_env
ARG server_protocol
ARG server_host
ARG server_port
ARG client_protocol
ARG client_host
ARG client_port
ARG manuscripts_table_columns
ARG manuscripts_table_first_column_width
ARG display_shortid_as_identifier
ARG review_shared
ARG review_hide
ARG hypothesis_allow_tagging
ARG allow_manual_import

ENV NODE_ENV "development"
ENV SERVER_PROTOCOL "http"
ENV SERVER_HOST "0.0.0.0"
ENV SERVER_PORT "3000"
ENV CLIENT_PROTOCOL "http"
ENV CLIENT_HOST "0.0.0.0"
ENV CLIENT_PORT "4000"
ENV INSTANCE_NAME $instance_name
ENV MANUSCRIPTS_TABLE_COLUMNS $manuscripts_table_columns
ENV MANUSCRIPTS_TABLE_FIRST_COLUMN_WIDTH $manuscripts_table_first_column_width
ENV DISPLAY_SHORTID_AS_IDENTIFIER $display_shortid_as_identifier
ENV REVIEW_SHARED $review_shared
ENV REVIEW_HIDE "true"
ENV HYPOTHESIS_ALLOW_TAGGING $hypothesis_allow_tagging
ENV HOME "/home/simplej"
ENV ALLOW_MANUAL_IMPORT $allow_manual_import


RUN mkdir -p ${HOME}
WORKDIR ${HOME}

# Only copy things needed for the yarn install
COPY package.json yarn.lock ./

# We do a development install because react-styleguidist is a dev dependency and we want to run tests
RUN [ "yarn", "install", "--frozen-lockfile" ]

ENV NODE_ENV ${NODE_ENV}

# Disabling the build for now, as it runs in the test server again
# RUN [ "npx", "pubsweet", "build"]

# The copy everything else that changes frequently
COPY . .
EXPOSE ${PORT}

CMD []

