FROM node:12.21-alpine

ARG instance_name
ARG node_env
ARG server_protocol
ARG server_host
ARG server_port
ARG client_protocol
ARG client_host
ARG client_port
ARG public_client_host
ARG public_client_protocol
ARG public_client_port
ARG manuscripts_table_columns
ARG manuscripts_table_first_column_width
ARG display_shortid_as_identifier
ARG review_shared
ARG review_hide
ARG hypothesis_allow_tagging
ARG allow_manual_import

ENV INSTANCE_NAME $instance_name
ENV NODE_ENV "production"
ENV SERVER_PROTOCOL "http"
ENV SERVER_HOST "localhost"
ENV SERVER_PORT "3000"
ENV CLIENT_PROTOCOL "http"
ENV CLIENT_HOST "0.0.0.0"
ENV CLIENT_PORT "4000"
ENV PUBLIC_CLIENT_HOST $public_client_host
ENV PUBLIC_CLIENT_PORT $public_client_port
ENV PUBLIC_CLIENT_PROTOCOL $public_client_protocol
ENV MANUSCRIPTS_TABLE_COLUMNS $manuscripts_table_columns
ENV MANUSCRIPTS_TABLE_FIRST_COLUMN_WIDTH $manuscripts_table_first_column_width
ENV DISPLAY_SHORTID_AS_IDENTIFIER $display_shortid_as_identifier
ENV REVIEW_SHARED $review_shared
ENV REVIEW_HIDE $review_hide
ENV HYPOTHESIS_ALLOW_TAGGING $hypothesis_allow_tagging
ENV ALLOW_MANUAL_IMPORT $allow_manual_import


RUN apk add --no-cache git python make g++ bash tar

WORKDIR /home/node/app

RUN mkdir ./uploads

COPY . .
RUN chown -R node:node .
ADD ./node_modules_dev.tar.gz .
RUN mv ./node_modules_dev ./node_modules && \
    yarn webpack --config webpack/webpack.production.config.js

RUN cp -r /home/node/app/_build/assets/* /home/node/app/_build

VOLUME /home/node/app/uploads

ENTRYPOINT ["sh", "./scripts/setupProdServer.sh"]
CMD ["node", "./startServer.js"]
