FROM cypress/browsers:node14.16.0-chrome89-ff86

ARG packagechanged
ARG node_env
ARG client_protocol
ARG client_host
ARG client_port

ENV NODE_ENV="development"
ENV SERVER_PROTOCOL="http"
ENV SERVER_HOST="0.0.0.0"
ENV SERVER_PORT="3000"
ENV CLIENT_PROTOCOL="http"
ENV CLIENT_HOST="0.0.0.0"
ENV CLIENT_PORT="4000"
ENV HOME="/home/simplej"

RUN mkdir -p ${HOME}
WORKDIR ${HOME}

# Only copy things needed for the yarn install
COPY package.json yarn.lock .yarnrc.yml ./

# We do a development install because react-styleguidist is a dev dependency and we want to run tests
RUN if [ -z "$packagechanged" ] ; then echo packagechanged not provided ; else [ "yarn", "install", "--immutable" ] ; fi

ENV NODE_ENV=${NODE_ENV}

# The copy everything else that changes frequently
COPY . .
EXPOSE ${PORT}

CMD []

