# docker
Dockerfile*
docker-compose*

# git
.git
.gitignore

# npm & yarn
node_modules
npm-debug.log
package-lock.json
yarn-error.log

# misc
.devcontainer
.DS_Store
.vscode
app.pid

# app
tmp/
uploads/*
