FROM cypress/browsers:node14.16.0-chrome89-ff86

ARG packagechanged
ARG instance_name
ARG node_env
ARG server_protocol
ARG server_host
ARG server_port
ARG client_protocol
ARG client_host
ARG client_port
ARG manuscripts_table_columns
ARG manuscripts_table_first_column_width
ARG display_shortid_as_identifier
ARG journal_name
ARG journal_abbreviated_name
ARG journal_homepage
ARG publishing_webhook_url
ARG publishing_webhook_secret
ARG hypothesis_api_key
ARG hypothesis_group
ARG crossref_login
ARG crossref_password
ARG crossref_registrant
ARG crossref_depositor_name
ARG crossref_depositor_email
ARG crossref_publication_type
ARG crossref_use_sandbox
ARG doi_prefix
ARG published_article_location_prefix
ARG publication_license_url
ARG review_shared
ARG review_hide

ENV NODE_ENV "development"
ENV SERVER_PROTOCOL "http"
ENV SERVER_HOST "0.0.0.0"
ENV SERVER_PORT "3000"
ENV CLIENT_PROTOCOL "http"
ENV CLIENT_HOST "0.0.0.0"
ENV CLIENT_PORT "4000"
ENV INSTANCE_NAME $instance_name
ENV MANUSCRIPTS_TABLE_COLUMNS $manuscripts_table_columns
ENV MANUSCRIPTS_TABLE_FIRST_COLUMN_WIDTH $manuscripts_table_first_column_width
ENV DISPLAY_SHORTID_AS_IDENTIFIER $display_shortid_as_identifier
ENV JOURNAL_NAME $journal_name
ENV JOURNAL_ABBREVIATED_NAME $journal_abbreviated_name
ENV JOURNAL_HOMEPAGE $journal_homepage
ENV PUBLISHING_WEBHOOK_URL $publishing_webhook_url
ENV PUBLISHING_WEBHOOK_SECRET $publishing_webhook_secret
ENV HYPOTHESIS_API_KEY $hypothesis_api_key
ENV HYPOTHESIS_GROUP $hypothesis_group
ENV CROSSREF_LOGIN $crossref_login
ENV CROSSREF_PASSWORD $crossref_password
ENV CROSSREF_REGISTRANT $crossref_registrant
ENV CROSSREF_DEPOSITOR_NAME $crossref_depositor_name
ENV CROSSREF_DEPOSITOR_EMAIL $crossref_depositor_email
ENV CROSSREF_PUBLICATION_TYPE $crossref_publication_type
ENV CROSSREF_USE_SANDBOX $crossref_use_sandbox
ENV DOI_PREFIX $doi_prefix
ENV PUBLISHED_ARTICLE_LOCATION_PREFIX $published_article_location_prefix
ENV PUBLICATION_LICENSE_URL $publication_license_url
ENV REVIEW_SHARED $review_shared
ENV REVIEW_HIDE $review_hide
ENV HOME "/home/simplej"

RUN mkdir -p ${HOME}
WORKDIR ${HOME}

# Only copy things needed for the yarn install
COPY package.json yarn.lock ./

# We do a development install because react-styleguidist is a dev dependency and we want to run tests
RUN if [ -z "$packagechanged" ] ; then echo packagechanged not provided ; else [ "yarn", "install", "--frozen-lockfile" ] ; fi

ENV NODE_ENV ${NODE_ENV}

# Disabling the build for now, as it runs in the test server again
# RUN [ "npx", "pubsweet", "build"]

# The copy everything else that changes frequently
COPY . .
EXPOSE ${PORT}

CMD []

