# This file is meant only for use in deploying through the project's ci pipeline
# Image values will be replaced during the pipeline run

version: '3'

services:
  client:
    image: kotahi/kotahi/client-preproduction:latest
    ports:
      - ${CLIENT_PORT}:4000
    environment:
      - SERVER_URL=${SERVER_URL}

  server:
    image: kotahi/kotahi/server-preproduction:latest
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ALLOW_SELF_SIGNED_CERTIFICATES=${POSTGRES_ALLOW_SELF_SIGNED_CERTIFICATES}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_URL=${SERVER_URL}
      - ORCID_CLIENT_ID=${ORCID_CLIENT_ID}
      - ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET}
      - USE_SANDBOXED_ORCID=${USE_SANDBOXED_ORCID:-false}
      - USE_COLAB_EMAIL=${USE_COLAB_EMAIL:-false}
      - KOTAHI_API_TOKENS=${KOTAHI_API_TOKENS}
      - JOURNAL_NAME=${JOURNAL_NAME}
      - JOURNAL_ABBREVIATED_NAME=${JOURNAL_ABBREVIATED_NAME}
      - JOURNAL_HOMEPAGE=${JOURNAL_HOMEPAGE}
      - GOOGLE_SPREADSHEET_CLIENT_EMAIL=${GOOGLE_SPREADSHEET_CLIENT_EMAIL}
      - GOOGLE_SPREADSHEET_PRIVATE_KEY=${GOOGLE_SPREADSHEET_PRIVATE_KEY}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - HYPOTHESIS_API_KEY=${HYPOTHESIS_API_KEY}
      - HYPOTHESIS_GROUP=${HYPOTHESIS_GROUP}
      - HYPOTHESIS_ALLOW_TAGGING=${HYPOTHESIS_ALLOW_TAGGING}
      - HYPOTHESIS_REVERSE_FIELD_ORDER=${HYPOTHESIS_REVERSE_FIELD_ORDER}
      - CROSSREF_LOGIN=${CROSSREF_LOGIN}
      - CROSSREF_PASSWORD=${CROSSREF_PASSWORD}
      - CROSSREF_REGISTRANT=${CROSSREF_REGISTRANT}
      - CROSSREF_DEPOSITOR_NAME=${CROSSREF_DEPOSITOR_NAME}
      - CROSSREF_DEPOSITOR_EMAIL=${CROSSREF_DEPOSITOR_EMAIL}
      - CROSSREF_PUBLICATION_TYPE=${CROSSREF_PUBLICATION_TYPE:-article}
      - CROSSREF_USE_SANDBOX=${CROSSREF_USE_SANDBOX:-false}
      - DOI_PREFIX=${DOI_PREFIX}
      - PUBLISHED_ARTICLE_LOCATION_PREFIX=${PUBLISHED_ARTICLE_LOCATION_PREFIX}
      - PUBLICATION_LICENSE_URL=${PUBLICATION_LICENSE_URL}
      - MANUSCRIPTS_TABLE_COLUMNS=${MANUSCRIPTS_TABLE_COLUMNS}
      - DISPLAY_SHORTID_AS_IDENTIFIER=${DISPLAY_SHORTID_AS_IDENTIFIER:-false}
      - GMAIL_NOTIFICATION_EMAIL_AUTH=${GMAIL_NOTIFICATION_EMAIL_AUTH}
      - GMAIL_NOTIFICATION_EMAIL_SENDER=${GMAIL_NOTIFICATION_EMAIL_SENDER}
      - GMAIL_NOTIFICATION_PASSWORD=${GMAIL_NOTIFICATION_PASSWORD}
      - PUBLISHING_WEBHOOK_URL=${PUBLISHING_WEBHOOK_URL}
      - PUBLISHING_WEBHOOK_TOKEN=${PUBLISHING_WEBHOOK_TOKEN}
      - PUBLISHING_WEBHOOK_REF=${PUBLISHING_WEBHOOK_REF}
      - REVIEW_SHARED=${REVIEW_SHARED:-false}
      - REVIEW_HIDE=${REVIEW_HIDE:-false}
      - NOTIFICATION_EMAIL_AUTOMATED=${NOTIFICATION_EMAIL_AUTOMATED:-false}
      - NOTIFICATION_EMAIL_CC_ENABLED=${NOTIFICATION_EMAIL_CC_ENABLED:-false}
      - SERVICE_ANYSTYLE_CLIENT_ID=${SERVICE_ANYSTYLE_CLIENT_ID}
      - SERVICE_ANYSTYLE_SECRET=${SERVICE_ANYSTYLE_SECRET}
      - SERVICE_ANYSTYLE_PROTOCOL=${SERVICE_ANYSTYLE_PROTOCOL}
      - SERVICE_ANYSTYLE_HOST=${SERVICE_ANYSTYLE_HOST}
      - SERVICE_ANYSTYLE_PORT=${SERVICE_ANYSTYLE_PORT}
      - SERVICE_PAGEDJS_CLIENT_ID=${SERVICE_PAGEDJS_CLIENT_ID}
      - SERVICE_PAGEDJS_SECRET=${SERVICE_PAGEDJS_SECRET}
      - SERVICE_PAGEDJS_PROTOCOL=${SERVICE_PAGEDJS_PROTOCOL}
      - SERVICE_PAGEDJS_HOST=${SERVICE_PAGEDJS_HOST}
      - SERVICE_PAGEDJS_PORT=${SERVICE_PAGEDJS_PORT}
      - SERVICE_XSWEET_CLIENT_ID=${SERVICE_XSWEET_CLIENT_ID}
      - SERVICE_XSWEET_SECRET=${SERVICE_XSWEET_SECRET}
      - SERVICE_XSWEET_PROTOCOL=${SERVICE_XSWEET_PROTOCOL}
      - SERVICE_XSWEET_HOST=${SERVICE_XSWEET_HOST}
      - SERVICE_XSWEET_PORT=${SERVICE_XSWEET_PORT}
      - S3_PROTOCOL=${S3_PROTOCOL}
      - S3_HOST=${S3_HOST}
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - AUTO_IMPORT_HOUR_UTC=${AUTO_IMPORT_HOUR_UTC}
      - DISABLE_EVENT_NOTIFICATIONS=${DISABLE_EVENT_NOTIFICATIONS}
      - ARCHIVE_PERIOD_DAYS=${ARCHIVE_PERIOD_DAYS}
      - ALLOW_MANUAL_IMPORT=${ALLOW_MANUAL_IMPORT}
      - SEMANTIC_SCHOLAR_IMPORTS_RECENCY_PERIOD_DAYS=${SEMANTIC_SCHOLAR_IMPORTS_RECENCY_PERIOD_DAYS}
      - TEAM_TIMEZONE=${TEAM_TIMEZONE}
      - FLAX_EXPRESS_PORT=${FLAX_EXPRESS_PORT}
      - FLAX_EXPRESS_HOST=${FLAX_EXPRESS_HOST}
      - FLAX_EXPRESS_PROTOCOL=${FLAX_EXPRESS_PROTOCOL}
      - FLAX_CLIENT_ID=${FLAX_CLIENT_ID}
      - FLAX_CLIENT_SECRET=${FLAX_CLIENT_SECRET}
      - FLAX_CLIENT_API_URL=${FLAX_CLIENT_API_URL}
      - FLAX_SITE_URL=${FLAX_SITE_URL}
      - USE_APERTURE_EMAIL=${USE_APERTURE_EMAIL}
      - INSTANCE_GROUPS=${INSTANCE_GROUPS}
      - USE_COLAB_BIOPHYSICS_IMPORT=${USE_COLAB_BIOPHYSICS_IMPORT}
      - E2E_TESTING_API=${E2E_TESTING_API}

  # kotahi-flax-site:
  #   image: cokoapps/kotahi-flax:0.2.41
  #   depends_on:
  #     - server
  #   ports:
  #     - ${FLAX_EXPRESS_PORT}:3000
  #     - ${FLAX_SITE_PORT}:80
  #   environment:
  #     - FLAX_EXPRESS_PORT=${FLAX_EXPRESS_PORT}
  #     - FLAX_CLIENT_ID=${FLAX_CLIENT_ID}
  #     - FLAX_CLIENT_SECRET=${FLAX_CLIENT_SECRET}
  #     - FLAX_CLIENT_API_URL=${FLAX_CLIENT_API_URL}
