apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - k8s.kotahi.cloud
    secretName: elife-kotahi-tls
  rules:
  - host: k8s.kotahi.cloud
    http:
      paths:
      - backend:
          serviceName: server
          servicePort: 80