apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: job-xsweet
  name: job-xsweet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: job-xsweet
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: job-xsweet
    spec:
      initContainers:
      - name: init-wait
        image: alpine
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 server {{ .Values.backend.ingress.port }} && exit 0 || sleep 3; done; exit 1"]
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: postgresql-database
                  name: "{{ .Values.rdssecret }}"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: postgresql-host
                  name: "{{ .Values.rdssecret }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: "{{ .Values.rdssecret }}"
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: postgresql-port
                  name: "{{ .Values.rdssecret }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgresql-username
                  name: "{{ .Values.rdssecret }}"
          image: "{{ .Values.images.jobxsweet.repository }}:{{ .Values.images.jobxsweet.tag }}"
          command: ["node"]
          args: ["src/xsweet.js"]
          name: job-xsweet
          resources: {}
      restartPolicy: Always
status: {}