app = 'kotahi-flax-main'
primary_region = 'lhr'

[build]
image = 'cokoapps/kotahi-flax:0.5.10'

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[services]]
protocol = 'tcp'
internal_port = 8081
auto_stop_machines = 'off'
auto_start_machines = true

[[services.ports]]
port = 8081
handlers = ['tls', 'http']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
FLAX_EXPRESS_PORT = '8081'
FLAX_CLIENT_API_URL = 'https://kotahi-server-main.fly.dev'
