# fly.toml app configuration file generated for kotahi-server-main on 2025-02-11T17:09:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kotahi-server-main'
primary_region = 'lhr'

# [build]
# image = 'cokoapps/kotahi-server:2025.02.11-0'

[env]
CLIENT_URL = 'https://kotahi-client-main.fly.dev'
FLAX_CLIENT_API_URL = 'https://kotahi-server-main.fly.dev'
FLAX_EXPRESS_HOST = 'kotahi-flax-main.fly.dev'
FLAX_EXPRESS_PORT = 8081
FLAX_EXPRESS_PROTOCOL = 'https'
FLAX_SITE_URL = 'http://kotahi-flax-main.fly.dev'
INSTANCE_GROUPS = 'journal:journal,prc:prc,single_form:preprint1,preprint2:preprint2'
MANUSCRIPTS_TABLE_COLUMNS = 'shortId, submission.$title, created, updated, status, author'
NODE_ENV = 'production'
SERVER_PORT = 8080
SERVER_URL = 'https://kotahi-server-main.fly.dev'
SERVICE_ANYSTYLE_HOST = 'anystyle-ms.fly.dev'
SERVICE_ANYSTYLE_PORT = ''
SERVICE_ANYSTYLE_PROTOCOL = 'https'
SERVICE_PAGEDJS_HOST = 'pagedjs-ms.fly.dev'
SERVICE_PAGEDJS_PORT = ''
SERVICE_PAGEDJS_PROTOCOL = 'https'
SERVICE_XSWEET_HOST = 'xsweet-ms.fly.dev'
SERVICE_XSWEET_PORT = ''
SERVICE_XSWEET_PROTOCOL = 'https'
USE_SANDBOXED_ORCID = 'true'
WS_YJS_SERVER_PORT = 8081

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[services]]
protocol = 'tcp'
internal_port = 8080

[[services.ports]]
port = 80
handlers = ['http']

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[[services]]
protocol = 'tcp'
internal_port = 8081

[[services.ports]]
port = 8081
handlers = ['tls', 'http']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
