app = 'kotahi-dev-docs'
primary_region = 'fra'

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
