name: Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Cache client deps
      #   uses: actions/cache@v4
      #   with:
      #     path: packages/client/node_modules
      #     key: client-${{ hashFiles('packages/client/yarn.lock') }}

      # - name: Cache server deps
      #   uses: actions/cache@v4
      #   with:
      #     path: packages/server/node_modules
      #     key: server-${{ hashFiles('packages/server/yarn.lock') }}

      # - name: Cache devdocs deps
      #   uses: actions/cache@v4
      #   with:
      #     path: packages/devdocs/node_modules
      #     key: devdocs-${{ hashFiles('packages/devdocs/yarn.lock') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Yarn global cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable
          cd packages/client && yarn install --immutable && cd ../..
          cd packages/server && yarn install --immutable && cd ../..
          cd packages/devdocs && yarn install --immutable && cd ../..

      - name: Lint
        run: yarn coko-lint run

  deploy_server:
    name: Deploy test server

    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: lint

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/server
          fly deploy -c ../../.fly/kotahi-server-test.toml --dockerfile ./Dockerfile-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_TEST_SERVER }}

  deploy_client:
    name: Deploy test client

    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: lint

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/client
          fly deploy -c ../../.fly/kotahi-client-test.toml --dockerfile ./Dockerfile-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_TEST_CLIENT }}
