name: Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          corepack enable
          yarn install
          cd packages/client
          yarn install
          cd ../server
          yarn install
          cd ../devdocs
          yarn install
          cd ../..

      - name: Lint
        run: yarn coko-lint run

  deploy_server:
    name: Deploy test server

    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: lint

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/server
          fly deploy -c ../../.fly/kotahi-server-test.toml --dockerfile ./Dockerfile-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_TEST_SERVER }}

  deploy_client:
    name: Deploy test client

    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: lint

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/client
          fly deploy -c ../../.fly/kotahi-client-test.toml --dockerfile ./Dockerfile-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_TEST_CLIENT }}
