name: Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable
          cd packages/client && yarn install --immutable && cd ../..
          cd packages/server && yarn install --immutable && cd ../..
          cd packages/devdocs && yarn install --immutable && cd ../..

      - name: Lint
        run: yarn coko-lint run

  e2e-journal:
    name: End to end tests - journal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Pull containers
        run: docker compose -f docker-compose.production.yml pull

      - name: Build containers
        run: docker compose -f docker-compose.production.yml build

      - name: Run containers
        run: docker compose -f docker-compose.production.yml up -d

      # - name: Wait for containers to be up and running
      #   run: |
      #     while ! nc -z localhost 4000; do sleep 1; done
      #     while ! nc -z localhost 4000; do sleep 1; done

      - name: Run tests
        run: yarn cypress run --spec cypress/e2e/a-journal

  deploy_server:
    name: Deploy test server

    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: lint

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/server
          fly deploy -c ../../.fly/kotahi-server-test.toml --dockerfile ./Dockerfile-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_TEST_SERVER }}

  deploy_client:
    name: Deploy test client

    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: lint

    runs-on: ubuntu-latest
    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd packages/client
          fly deploy -c ../../.fly/kotahi-client-test.toml --dockerfile ./Dockerfile-production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_TEST_CLIENT }}
