name: Lint

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          corepack enable
          yarn install
          cd packages/client
          yarn install
          cd ../server
          yarn install
          cd ../..

      - name: Lint
        run: yarn coko-lint run
