name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  # ------------------------
  # Release (manual, main only)
  # ------------------------
  release:
    name: Release

    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment: release
    concurrency: release

    outputs:
      release_version: ${{ steps.set_version.outputs.release_version }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run release
        id: set_version
        run: |
          node scripts/updatePackageJson.js
          VERSION=$(node -e "const pkg=require('./package.json');console.log(pkg.version)")
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT
          git add -A
          git commit -m "release version $VERSION [skip ci]" || echo "No changes to commit"
          git tag $VERSION || (git tag -d $VERSION && git tag $VERSION)
          git push origin HEAD:main --tags

  # ------------------------
  # Publish (DockerHub)
  # ------------------------
  publish_client:
    name: Publish client

    if: github.ref == 'refs/heads/main'
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker push client
        run: |
          cd packages/client
          docker build -t cokoapps/kotahi-client:${{ needs.release.outputs.release_version }} -f Dockerfile-production .
          docker push cokoapps/kotahi-client:${{ needs.release.outputs.release_version }}

  publish_server:
    name: Publish server

    if: github.ref == 'refs/heads/main'
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker push server
        run: |
          cd packages/server
          docker build -t cokoapps/kotahi-server:${{ needs.release.outputs.release_version }} -f Dockerfile-production .
          docker push cokoapps/kotahi-server:${{ needs.release.outputs.release_version }}

  publish_docs:
    name: Publish docs

    if: github.ref == 'refs/heads/main'
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker push docs
        run: |
          cd packages/devdocs
          docker build -t ghcr.io/${{ github.repository }}/devdocs:${{ github.sha }} -f Dockerfile-production .
          docker push ghcr.io/${{ github.repository }}/devdocs:${{ github.sha }}

  deploy_docs:
    name: Deploy docs

    if: github.ref == 'refs/heads/main'
    needs: [publish_docs]
    runs-on: ubuntu-latest

    container:
      image: cokoapps/fly

    steps:
      - uses: actions/checkout@v4

      - name: Deploy docs to fly
        run: fly deploy -c .fly/kotahi-dev-docs.toml --image ghcr.io/${{ github.repository }}/devdocs:${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEV_DOCS_TOKEN }}
